### ISSUE TITLE
Ajouter la possibilié de saisir un mail pour recevoir les liens de votes et de résultats

### ISSUE THREAD

**Issue by oceanBigOne** [MieuxVoter/majority-judgment-web-app#35]
- [ ] Front @oceanBigOne 
- [ ] Back @guhur

**Comment by guhur** [comment]
This should be easily achieved by writing a new Next Js function

**Comment by guhur** [comment]
This is not relevant in v2 anymore. Indeed, we have now an admin panel with links to vote and results & we can receive the admin panel link by email.
