### ISSUE TITLE
Dates are not editable (Safari MacOS)

### ISSUE THREAD

**Issue by thuenen** [MieuxVoter/majority-judgment-web-app#56]
### Issue and Steps to Reproduce

When creating an election with a terminal time/date, it won't allow to change the date, only the time.
I used Safari on MacOS 10.15.5 .

### Screenshots
<img width="1070" alt="Screenshot 2020-06-17 at 21 00 55" src="https://user-images.githubusercontent.com/63877257/84944782-9959fe80-b0e6-11ea-952a-a2feeae7cda0.png">

#### Expected
Change the dates :)

**Comment by guhur** [comment]
Hi!
We updated dependencies. Could you check if this problem still occurs? I don't have any macos with me here.
Thanks!
