### ISSUE TITLE
Option pour désactiver l'ordonnancement aléatoire des propositions

### ISSUE THREAD

**Issue by jeromekasparian** [MieuxVoter/majority-judgment-web-app#86]
Une option pour désactiver l'ordonnancement aléatoire des propositions faciliterait l'usage dans certains cas : 
	- en usage réel, lorsque les propositions ont un lien entre elles : relation d'ordre (couleur de la plus claire à la plus foncée, horaire / date) ou autres relations logiques (3 scénarios et leurs variantes)
	- en usage pédagogique, pour pouvoir afficher au tableau le "bulletin de vote" et accompagner les élèves, c'est plus facile si les élèves ont les choix dans l'ordre affiché au tableau.
	- pour saisir a posteriori des bulletins de vote papier, et utiliser l'app seulement pour le traitement

**Comment by guhur** [comment]
Hi @jeromekasparian! 
Sorry, it took a while, but we added your feature in newly-built version :-) 
See PR#89 for details!
