### ISSUE TITLE
A 5 options, laisser des choix positifs ET négatifs

### ISSUE THREAD

**Issue by jeromekasparian** [MieuxVoter/majority-judgment-web-app#88]
### Suggestion

Lorsque le nombre d'option est réduit, il me semblerait logique de conserver l'amplitude de l'échelle des choix (d'excellent à à rejeter), ou du moins sa symétrie. Par exemple, en réduisant à 5 options, on perd actuellement pour ainsi dire les deux mentions négatives. Il me semblerait plus logique de conserver Ex / B / AB / P / AR ou TB / B / AB / P / I.

**Comment by guhur** [comment]
This is fixed in the v2 :-)
