### ISSUE TITLE
La mention affichée n'est pas bonne

### ISSUE THREAD

**Issue by TheoSabattie** [MieuxVoter/majority-judgment-web-app#93]
### Issue and Steps to Reproduce
- Créer un vote avec deux choix
- Ajouter la mention à rejeter
- Voter une seule fois, un entre bien, l'autre en à rejeter
- ouvrir les resultats actuel
Le "à rejeter" a pour mention "très bien" 

### Screenshots
![Screenshot_20221205_195051_com android chrome](https://user-images.githubusercontent.com/2721436/205742396-c4e31add-125d-47cf-85ec-53b3522a6b86.jpg)

### Link to an example failed election
https://deploy-preview-89--mieuxvoter-app-ui.netlify.app/result/kos-xmt-fvix

#### Expected
- mention à rejeter

**Comment by guhur** [comment]
This is fixed in 5a97403 (along with a few mistakes in the rendering of the profile merit!)
