### ISSUE TITLE
UX - qu'est-ce qui est random ? 

### ISSUE THREAD

**Issue by TheoSabattie** [MieuxVoter/majority-judgment-web-app#94]
### Issue and Steps to Reproduce
J'ai remarqué que l'on pouvait ordonner les mentions uniquement (drag and drop) 
Sur la page qui affiche les mentions, je remarque un "Ordre Aleatoire"  

Est-ce que ça concerne les mentions ? (ça me semble bizarre comme option) 
Ou ça concerne les propositions présentes sur la page précédente ? 
Si oui, suggestion:
- mettre sur la page precedente
Ou
- être plus spécifique dans la description 

![Screenshot_20221205_194740_com android chrome](https://user-images.githubusercontent.com/2721436/205743247-f1406376-d3f8-4e47-bd96-8524de45e68e.jpg)

**Comment by guhur** [comment]
Hi @TheoSabattie!
This is another very good point. I fixed it in commit 481fb43.
Thanks for your detailed feedback!
