### ISSUE TITLE
Style sur mobile "bizarre" 

### ISSUE THREAD

**Issue by TheoSabattie** [MieuxVoter/majority-judgment-web-app#95]
### Issue and Steps to Reproduce

Regarder le site sur mobile
-> une marge apparaît à droite et en bas. Cela donne l'impression que tout est cassé car beaucoup d'input/visus dépassent de la zone principale. 
Je ne sais pas si c'est volontaire (?) 

### Screenshots
![Screenshot_20221206_071809_com android chrome](https://user-images.githubusercontent.com/2721436/205836381-4b8b4dc4-e176-45b7-a498-300b0d4aac16.jpg)
![Screenshot_20221206_071815_com android chrome](https://user-images.githubusercontent.com/2721436/205836399-9b69ce87-24e3-4fc5-8033-52f3286f12dd.jpg)

### Link to an example failed election
Homescreen

**Comment by guhur** [comment]
Fix in  95dd812 ! Thanks!
